In [4]:
import numpy as np

In [5]:
a = np.zeros(10)
a

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [6]:
b = np.zeros([10,10])

In [7]:
b

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [8]:
c = np.arange(10)

In [9]:
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
for i in c:
    print i

0
1
2
3
4
5
6
7
8
9


In [11]:
c[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [12]:
d = range(10)

In [13]:
d

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [16]:
d[::-2]

[9, 7, 5, 3, 1]

In [17]:
e = np.eye(10)

In [19]:
e

array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.]])

In [20]:
f = np.random.random(5)

In [22]:
f

array([ 0.33419085,  0.97782068,  0.86163388,  0.09867541,  0.25024778])

In [26]:
g = np.random.random((3,3))

In [27]:
g

array([[ 0.08332379,  0.39752938,  0.69455447],
       [ 0.44547999,  0.59446559,  0.46982739],
       [ 0.60068204,  0.02134611,  0.71300874]])