In [3]:
import numpy as np
import pandas as pd

In [4]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
a.size

10

In [8]:
a.itemsize

8

In [9]:
b = np.zeros([10,10])
b

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [10]:
c = np.arange(10)
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
for i in c:
    print(i)
#倒叙循环
c[::-1]

0
1
2
3
4
5
6
7
8
9


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [14]:
d = range(10)
d[::-2]

range(9, -1, -2)

In [17]:
d1 = list(range(10))
# d1
d1[::-2]

[9, 7, 5, 3, 1]

In [18]:
e = np.eye(10)
e

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [19]:
f = np.random.random(5)
f

array([0.83029769, 0.79486076, 0.14194079, 0.90716024, 0.0409429 ])

In [20]:
g = np.random.random((3,3))
g

array([[0.5337766 , 0.23218197, 0.65024989],
       [0.67300721, 0.71740447, 0.53723108],
       [0.45849898, 0.08958526, 0.97414702]])

In [21]:
df = pd.DataFrame({'A':range(1,5),'B':range(6,10)})
df

A  B
0  1  6
1  2  7
2  3  8
3  4  9

In [22]:
f[0]=0
f

array([0.        , 0.79486076, 0.14194079, 0.90716024, 0.0409429 ])

In [24]:
h = np.arange(10,50)
h=h[::-1]
h

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [25]:
i = np.arange(9)
i

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [26]:
k = [0,1,1,2,2,0],
np.nonzero(k)

(array([0, 0, 0, 0], dtype=int64), array([1, 2, 3, 4], dtype=int64))

In [27]:
j = i.reshape(3,3)
np.nonzero(j)

(array([0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [28]:
j

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [30]:
l = np.random.random((3,3,4))

l

array([[[0.61313845, 0.11749494, 0.41668512, 0.96717501],
        [0.34801743, 0.50163744, 0.24521585, 0.43718137],
        [0.21109344, 0.13028013, 0.05026209, 0.55020907]],

       [[0.88225119, 0.04856389, 0.58579186, 0.46170919],
        [0.95066384, 0.29749758, 0.2855761 , 0.34053002],
        [0.19998519, 0.06796271, 0.2515415 , 0.81873635]],

       [[0.28864213, 0.00604647, 0.64536699, 0.7481846 ],
        [0.85877328, 0.7653738 , 0.87266105, 0.53586615],
        [0.63844451, 0.37354721, 0.88305711, 0.22125924]]])

In [34]:
m = np.random.random((10,10))
print(m.max())
print(m.min())
m.mean()

0.9968121280210496
0.006324933972872593


0.48451561499214063

In [35]:
o = np.zeros((5,5))

In [36]:
o

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [37]:
o[:,[0,-1]]=1

In [38]:
o

array([[1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.]])

In [39]:
o[[0,-1],:]=1

In [40]:
o

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [41]:
# 前面2行 ！
o[:2]

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.]])

In [42]:
o[:,:2]

array([[1., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 1.]])

In [43]:
p = np.arange(2,9)

In [44]:
p

array([2, 3, 4, 5, 6, 7, 8])

In [46]:
np.pad(p,pad_width=2,mode='constant',constant_values=0)

array([0, 0, 2, 3, 4, 5, 6, 7, 8, 0, 0])

In [47]:
np.pad(o,pad_width=1,mode='constant',constant_values=9)

array([[9., 9., 9., 9., 9., 9., 9.],
       [9., 1., 1., 1., 1., 1., 9.],
       [9., 1., 0., 0., 0., 1., 9.],
       [9., 1., 0., 0., 0., 1., 9.],
       [9., 1., 0., 0., 0., 1., 9.],
       [9., 1., 1., 1., 1., 1., 9.],
       [9., 9., 9., 9., 9., 9., 9.]])

In [48]:
vector=np.diag(np.arange(1,5),k=-1)

In [49]:
vector

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [53]:
vector=np.zeros((8,8))
# 偶数行 ，奇数列
vector[::2,1::2]=1
vector
# vector[1::2,::2]=1

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [52]:
vector

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [54]:
x = np.arange(0,100,5)
x

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [55]:
y=np.where(x%2==0)
y

(array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18], dtype=int64),)

In [56]:
x[y]

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [58]:
z=np.where(x==10)

In [59]:
0*np.nan

nan

In [60]:
np.nan == np.nan

False

In [61]:
np.inf

inf