In [1]:
import numpy as np

In [9]:
a= np.array([[1, 2,3], [3, 4,5]],dtype=np.float)

In [3]:
np.mean(a,axis=1)

array([2., 4.])

In [4]:
a

array([[1, 2, 3],
       [3, 4, 5]])

In [5]:
a[0]

array([1, 2, 3])

In [6]:
np.mean(a)

3.0

In [10]:
a

array([[1., 2., 3.],
       [3., 4., 5.]])

In [20]:
np.logspace(0,10,9)

array([1.00000000e+00, 1.77827941e+01, 3.16227766e+02, 5.62341325e+03,
       1.00000000e+05, 1.77827941e+06, 3.16227766e+07, 5.62341325e+08,
       1.00000000e+10])

In [21]:
10/9

1.1111111111111112

In [24]:
10**1.25

17.78279410038923

In [23]:
10**2.333333

215.4433036442785

In [25]:
def funcA(i,j):
    return i+j

In [26]:
np.fromfunction(funcA,(3,3))

array([[0., 1., 2.],
       [1., 2., 3.],
       [2., 3., 4.]])

In [27]:
np.arange(1,10,1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
a=np.arange(0,16,1)

In [29]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [30]:
b=a[:5]

In [31]:
b

array([0, 1, 2, 3, 4])

In [32]:
b[1]=99

In [33]:
b

array([ 0, 99,  2,  3,  4])

In [34]:
a

array([ 0, 99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [37]:
c=a[[0,2,4,6,1]]

In [38]:
c

array([ 0,  2,  4,  6, 99])

In [39]:
c[-1]=11

In [40]:
c

array([ 0,  2,  4,  6, 11])

In [41]:
a

array([ 0, 99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])