In [1]:
import numpy as np
import pandas as pd

In [2]:
a = np.zeros(10)
a

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [19]:
a.size

10

In [20]:
a.itemsize

8

In [3]:
b = np.zeros([10,10])

In [4]:
b

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [5]:
c = np.arange(10)

In [6]:
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
for i in c:
    print i

0
1
2
3
4
5
6
7
8
9


In [8]:
c[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [9]:
d = range(10)

In [10]:
d

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [11]:
d[::-2]

[9, 7, 5, 3, 1]

In [12]:
e = np.eye(10)

In [13]:
e

array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.]])

In [14]:
f = np.random.random(5)

In [15]:
f

array([ 0.38057448,  0.36372866,  0.05967583,  0.63293602,  0.02410587])

In [16]:
g = np.random.random((3,3))

In [17]:
g

array([[ 0.13896555,  0.13476217,  0.22579441],
       [ 0.33627841,  0.28272996,  0.15837884],
       [ 0.97000672,  0.43846976,  0.37877247]])

In [22]:
df = pd.DataFrame({'A':range(1,5),'B':range(6,10)})

In [23]:
df

A  B
0  1  6
1  2  7
2  3  8
3  4  9

In [27]:
f[0]=0

In [28]:
f

array([ 0.        ,  0.36372866,  0.05967583,  0.63293602,  0.02410587])

In [29]:
h = np.arange(10,50)

In [32]:
h=h[::-1]

In [34]:
h

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [38]:
i = np.arange(9)


In [39]:
i

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [41]:
j = i.reshape(3,3)

In [45]:
k = [0,1,1,2,2,0]
np.nonzero(k)

(array([1, 2, 3, 4]),)

In [46]:
np.nonzero(j)

(array([0, 0, 1, 1, 1, 2, 2, 2]), array([1, 2, 0, 1, 2, 0, 1, 2]))

In [47]:
j

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [49]:
l = np.random.random((3,3,3))

In [50]:
l

array([[[ 0.05741561,  0.48847203,  0.8376888 ],
        [ 0.76480078,  0.61015175,  0.44216691],
        [ 0.26500863,  0.2716134 ,  0.86840874]],

       [[ 0.18753769,  0.46202449,  0.22077446],
        [ 0.84980799,  0.71594131,  0.55984924],
        [ 0.70242954,  0.79848729,  0.0917165 ]],

       [[ 0.75193954,  0.44668368,  0.68174661],
        [ 0.32038481,  0.05873683,  0.4592638 ],
        [ 0.70110955,  0.20220421,  0.13716221]]])

In [52]:
m = np.random.random((10,10))
print m.max()
print m.min()

0.995481756512
0.00425779492297


In [53]:
m

array([[ 0.77681637,  0.65528593,  0.30750482,  0.31005653,  0.26446902,
         0.54494011,  0.20929428,  0.91934818,  0.16180049,  0.50364045],
       [ 0.64684675,  0.30118647,  0.51268148,  0.08322828,  0.04249915,
         0.60516716,  0.58350489,  0.31322555,  0.37154612,  0.6681878 ],
       [ 0.7442801 ,  0.5239037 ,  0.45885352,  0.18320748,  0.21771857,
         0.25815218,  0.74891991,  0.51278031,  0.00425779,  0.05135066],
       [ 0.00600388,  0.80714625,  0.13791627,  0.41670307,  0.02938266,
         0.118381  ,  0.01103824,  0.90243515,  0.71469877,  0.86149003],
       [ 0.47654571,  0.13571859,  0.22530452,  0.39735794,  0.00571096,
         0.11020357,  0.10967935,  0.55868553,  0.20275403,  0.55500359],
       [ 0.89615143,  0.2095011 ,  0.09131126,  0.31413325,  0.95110664,
         0.69621918,  0.1813132 ,  0.68923607,  0.08029172,  0.75122225],
       [ 0.63307613,  0.61980024,  0.2415376 ,  0.41061314,  0.19521858,
         0.86597018,  0.16517886,  0.94935235

In [54]:
m.mean()

0.46234440949751954

In [55]:
o = np.zeros((5,5))

In [56]:
o

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [58]:
o[:,[0,-1]]=1

In [59]:
o

array([[ 1.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  1.]])

In [60]:
o[:2]

array([[ 1.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  1.]])

In [61]:
o[:,:2]

array([[ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.]])

In [63]:
o[[0,-1],:]=1

In [64]:
o

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [65]:
p = np.arange(2,9)

In [66]:
np.pad(p,pad_width=1,mode='constant',constant_values=0)

array([0, 2, 3, 4, 5, 6, 7, 8, 0])

In [67]:
0*np.nan

nan

In [68]:
np.nan == np.nan

False

In [69]:
np.inf

inf

In [70]:
vector=np.diag(np.arange(1,5),k=-1)

In [71]:
vector

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [72]:
vector=np.zeros((8,8))
vector[::2,1::2]=1
vector[1::2,::2]=1

In [73]:
vector

array([[ 0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.],
       [ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.],
       [ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.],
       [ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.],
       [ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.]])

In [4]:
x = np.arange(0,100,5)

In [5]:
x

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [7]:
y=np.where(x%2==0)

In [12]:
y

(array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18]),)

In [9]:
x[y]

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [10]:
z=np.where(x==10)

In [11]:
z

(array([2]),)