In [29]:
import pip
from sklearn.cross_validation import train_test_split
from sklearn.datasets import load_iris
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression

In [9]:
pip_list = pip.get_installed_distributions()

AttributeError: module 'pip' has no attribute 'get_installed_distributions'

In [10]:
iris = load_iris()

In [ ]:
iris

In [10]:
iris.data[0]

array([5.1, 3.5, 1.4, 0.2])

In [16]:
data_df =pd.DataFrame(iris.data,columns=['x1','x2','x3','x4'])

In [25]:
data_df.tail()

x1   x2   x3   x4
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

In [17]:
target_df = pd.DataFrame(iris.target,columns=['xid'])

In [28]:
target_df.tail()

xid
145    2
146    2
147    2
148    2
149    2

In [18]:
df=data_df.copy()

In [30]:
df.tail()

x1   x2   x3   x4
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

In [19]:
df['xid']=iris.target

In [32]:
df.tail()

x1   x2   x3   x4  xid
145  6.7  3.0  5.2  2.3    2
146  6.3  2.5  5.0  1.9    2
147  6.5  3.0  5.2  2.0    2
148  6.2  3.4  5.4  2.3    2
149  5.9  3.0  5.1  1.8    2

In [37]:
df['xid'].value_counts()

2    50
1    50
0    50
Name: xid, dtype: int64

In [20]:
df.loc[df['xid']==0,'name']='virginica'

In [21]:
df.loc[df['xid']==1,'name']='visetosa'

In [22]:
df.loc[df['xid']==2,'name']='versicolor'

In [23]:
df.describe()

x1          x2          x3          x4         xid
count  150.000000  150.000000  150.000000  150.000000  150.000000
mean     5.843333    3.054000    3.758667    1.198667    1.000000
std      0.828066    0.433594    1.764420    0.763161    0.819232
min      4.300000    2.000000    1.000000    0.100000    0.000000
25%      5.100000    2.800000    1.600000    0.300000    0.000000
50%      5.800000    3.000000    4.350000    1.300000    1.000000
75%      6.400000    3.300000    5.100000    1.800000    2.000000
max      7.900000    4.400000    6.900000    2.500000    2.000000

In [24]:
df['name'].value_counts()

virginica     50
versicolor    50
visetosa      50
Name: name, dtype: int64

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
x1      150 non-null float64
x2      150 non-null float64
x3      150 non-null float64
x4      150 non-null float64
xid     150 non-null int32
name    150 non-null object
dtypes: float64(4), int32(1), object(1)
memory usage: 6.5+ KB


In [ ]:
df.head(100)

In [14]:
x=np.arange(16).reshape((4,4))

In [15]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [45]:
d1=pd.DataFrame(x,columns=['a','b','c','d'])

In [46]:
d1

a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [47]:
d1.values

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [50]:
d1[['a']]

a
0   0
1   4
2   8
3  12

In [25]:
x=df[['x1','x2','x3','x4']]
y=df[['xid']]

In [ ]:
x

In [ ]:
y

In [26]:
X_train,X_test,y_train,y_test = train_test_split(x,y,random_state=0)

In [27]:
X_train.tail()

x1   x2   x3   x4
9    4.9  3.1  1.5  0.1
103  6.3  2.9  5.6  1.8
67   5.8  2.7  4.1  1.0
117  7.7  3.8  6.7  2.2
47   4.6  3.2  1.4  0.2

In [28]:
y_train.tail()

xid
9      0
103    2
67     1
117    2
47     0

In [30]:
linear_mode = LinearRegression()
linear_mode.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [32]:
y_predict = linear_mode.predict(X_test)

In [33]:
y_predict

array([[ 2.07736575],
       [ 0.96756558],
       [-0.15999367],
       [ 1.82296218],
       [-0.03605266],
       [ 2.28586312],
       [-0.03498114],
       [ 1.31023544],
       [ 1.27219459],
       [ 1.10831334],
       [ 1.59874635],
       [ 1.3001601 ],
       [ 1.23847686],
       [ 1.32183582],
       [ 1.35022121],
       [-0.07018192],
       [ 1.36919126],
       [ 1.25533749],
       [ 0.03526429],
       [-0.04942159],
       [ 1.82590317],
       [ 1.42797071],
       [ 0.1016569 ],
       [ 0.04201595],
       [ 1.59282272],
       [-0.11363412],
       [ 0.15970569],
       [ 1.1706936 ],
       [ 0.93104142],
       [ 0.10501422],
       [ 1.74177991],
       [ 1.45864189],
       [-0.06928678],
       [ 1.62979205],
       [ 2.00484287],
       [ 1.27929066],
       [-0.0429807 ],
       [ 1.59202833]])