In [1]:
import pip

In [2]:
pip.get_installed_distributions()

[zxing 0.9.3 (c:\python3_64\lib\site-packages),
 zope.interface 4.5.0 (c:\python3_64\lib\site-packages),
 yarl 1.2.6 (c:\python3_64\lib\site-packages),
 xlwt 1.3.0 (c:\python3_64\lib\site-packages),
 xlrd 1.1.0 (c:\python3_64\lib\site-packages),
 wxpy 0.3.9.8 (c:\python3_64\lib\site-packages),
 widgetsnbextension 3.4.0 (c:\python3_64\lib\site-packages),
 wheel 0.31.1 (c:\python3_64\lib\site-packages),
 Werkzeug 0.14.1 (c:\python3_64\lib\site-packages),
 webencodings 0.5.1 (c:\python3_64\lib\site-packages),
 wcwidth 0.1.7 (c:\python3_64\lib\site-packages),
 w3lib 1.19.0 (c:\python3_64\lib\site-packages),
 virtualenvwrapper-win 1.2.5 (c:\python3_64\lib\site-packages),
 virtualenv 16.0.0 (c:\python3_64\lib\site-packages),
 virtualenv-clone 0.3.0 (c:\python3_64\lib\site-packages),
 urllib3 1.23 (c:\python3_64\lib\site-packages),
 tzlocal 1.5.1 (c:\python3_64\lib\site-packages),
 Twisted 18.7.0 (c:\python3_64\lib\site-packages),
 tushare 1.2.12 (c:\python3_64\lib\site-packages),
 treq 18.6.

In [4]:
from sklearn.datasets import load_iris

In [5]:
iris = load_iris()

In [7]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [10]:
iris.data[0]

array([5.1, 3.5, 1.4, 0.2])

In [24]:
data_df =pd.DataFrame(iris.data,columns=['x1','x2','x3','x4'])

In [25]:
data_df.tail()

x1   x2   x3   x4
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

In [26]:
target_df = pd.DataFrame(iris.target,columns=['xid'])

In [28]:
target_df.tail()

xid
145    2
146    2
147    2
148    2
149    2

In [29]:
df=data_df.copy()

In [30]:
df.tail()

x1   x2   x3   x4
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

In [31]:
df['xid']=iris.target

In [32]:
df.tail()

x1   x2   x3   x4  xid
145  6.7  3.0  5.2  2.3    2
146  6.3  2.5  5.0  1.9    2
147  6.5  3.0  5.2  2.0    2
148  6.2  3.4  5.4  2.3    2
149  5.9  3.0  5.1  1.8    2

In [37]:
df['xid'].value_counts()

2    50
1    50
0    50
Name: xid, dtype: int64

In [34]:
df.loc[df['xid']==0,'name']='virginica'

In [39]:
df.loc[df['xid']==1,'name']='visetosa'

In [40]:
df.loc[df['xid']==2,'name']='versicolor'

In [41]:
df.describe()

x1          x2          x3          x4         xid
count  150.000000  150.000000  150.000000  150.000000  150.000000
mean     5.843333    3.054000    3.758667    1.198667    1.000000
std      0.828066    0.433594    1.764420    0.763161    0.819232
min      4.300000    2.000000    1.000000    0.100000    0.000000
25%      5.100000    2.800000    1.600000    0.300000    0.000000
50%      5.800000    3.000000    4.350000    1.300000    1.000000
75%      6.400000    3.300000    5.100000    1.800000    2.000000
max      7.900000    4.400000    6.900000    2.500000    2.000000

In [42]:
df['name'].value_counts()

versicolor    50
virginica     50
visetosa      50
Name: name, dtype: int64

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
x1      150 non-null float64
x2      150 non-null float64
x3      150 non-null float64
x4      150 non-null float64
xid     150 non-null int32
name    150 non-null object
dtypes: float64(4), int32(1), object(1)
memory usage: 6.5+ KB


In [ ]:
df.head(100)

In [11]:
import numpy as np
import pandas as pd


In [14]:
x=np.arange(16).reshape((4,4))

In [15]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [45]:
d1=pd.DataFrame(x,columns=['a','b','c','d'])

In [46]:
d1

a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [47]:
d1.values

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [50]:
d1[['a']]

a
0   0
1   4
2   8
3  12

In [51]:
x=df[['x1','x2','x3','x4']]
y=df[['xid']]

In [52]:
x

x1   x2   x3   x4
0    5.1  3.5  1.4  0.2
1    4.9  3.0  1.4  0.2
2    4.7  3.2  1.3  0.2
3    4.6  3.1  1.5  0.2
4    5.0  3.6  1.4  0.2
5    5.4  3.9  1.7  0.4
6    4.6  3.4  1.4  0.3
7    5.0  3.4  1.5  0.2
8    4.4  2.9  1.4  0.2
9    4.9  3.1  1.5  0.1
10   5.4  3.7  1.5  0.2
11   4.8  3.4  1.6  0.2
12   4.8  3.0  1.4  0.1
13   4.3  3.0  1.1  0.1
14   5.8  4.0  1.2  0.2
15   5.7  4.4  1.5  0.4
16   5.4  3.9  1.3  0.4
17   5.1  3.5  1.4  0.3
18   5.7  3.8  1.7  0.3
19   5.1  3.8  1.5  0.3
20   5.4  3.4  1.7  0.2
21   5.1  3.7  1.5  0.4
22   4.6  3.6  1.0  0.2
23   5.1  3.3  1.7  0.5
24   4.8  3.4  1.9  0.2
25   5.0  3.0  1.6  0.2
26   5.0  3.4  1.6  0.4
27   5.2  3.5  1.5  0.2
28   5.2  3.4  1.4  0.2
29   4.7  3.2  1.6  0.2
..   ...  ...  ...  ...
120  6.9  3.2  5.7  2.3
121  5.6  2.8  4.9  2.0
122  7.7  2.8  6.7  2.0
123  6.3  2.7  4.9  1.8
124  6.7  3.3  5.7  2.1
125  7.2  3.2  6.0  1.8
126  6.2  2.8  4.8  1.8
127  6.1  3.0  4.9  1.8
128  6.4  2.8  5.6  2.1
129  7.2  3.0  5.8  1.6
130  7.4  2.8  6.1  1.9
131  7.9  3.8  6.4  2.0
132  6.4  2.8  5.6  2.2
133  6.3  2.8  5.1  1.5
134  6.1  2.6  5.6  1.4
135  7.7  3.0  6.1  2.3
136  6.3  3.4  5.6  2.4
137  6.4  3.1  5.5  1.8
138  6.0  3.0  4.8  1.8
139  6.9  3.1  5.4  2.1
140  6.7  3.1  5.6  2.4
141  6.9  3.1  5.1  2.3
142  5.8  2.7  5.1  1.9
143  6.8  3.2  5.9  2.3
144  6.7  3.3  5.7  2.5
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

[150 rows x 4 columns]

In [53]:
y

xid
0      0
1      0
2      0
3      0
4      0
5      0
6      0
7      0
8      0
9      0
10     0
11     0
12     0
13     0
14     0
15     0
16     0
17     0
18     0
19     0
20     0
21     0
22     0
23     0
24     0
25     0
26     0
27     0
28     0
29     0
..   ...
120    2
121    2
122    2
123    2
124    2
125    2
126    2
127    2
128    2
129    2
130    2
131    2
132    2
133    2
134    2
135    2
136    2
137    2
138    2
139    2
140    2
141    2
142    2
143    2
144    2
145    2
146    2
147    2
148    2
149    2

[150 rows x 1 columns]

In [54]:
from sklearn.cross_validation import train_test_split

In [55]:
X_train,X_test,y_train,y_test = train_test_split(x,y,random_state=0)

In [56]:
X_train

x1   x2   x3   x4
61   5.9  3.0  4.2  1.5
92   5.8  2.6  4.0  1.2
112  6.8  3.0  5.5  2.1
2    4.7  3.2  1.3  0.2
141  6.9  3.1  5.1  2.3
43   5.0  3.5  1.6  0.6
10   5.4  3.7  1.5  0.2
60   5.0  2.0  3.5  1.0
116  6.5  3.0  5.5  1.8
144  6.7  3.3  5.7  2.5
119  6.0  2.2  5.0  1.5
108  6.7  2.5  5.8  1.8
69   5.6  2.5  3.9  1.1
135  7.7  3.0  6.1  2.3
56   6.3  3.3  4.7  1.6
80   5.5  2.4  3.8  1.1
123  6.3  2.7  4.9  1.8
133  6.3  2.8  5.1  1.5
106  4.9  2.5  4.5  1.7
146  6.3  2.5  5.0  1.9
50   7.0  3.2  4.7  1.4
147  6.5  3.0  5.2  2.0
85   6.0  3.4  4.5  1.6
30   4.8  3.1  1.6  0.2
101  5.8  2.7  5.1  1.9
94   5.6  2.7  4.2  1.3
64   5.6  2.9  3.6  1.3
89   5.5  2.5  4.0  1.3
91   6.1  3.0  4.6  1.4
125  7.2  3.2  6.0  1.8
..   ...  ...  ...  ...
14   5.8  4.0  1.2  0.2
122  7.7  2.8  6.7  2.0
19   5.1  3.8  1.5  0.3
29   4.7  3.2  1.6  0.2
130  7.4  2.8  6.1  1.9
49   5.0  3.3  1.4  0.2
136  6.3  3.4  5.6  2.4
99   5.7  2.8  4.1  1.3
82   5.8  2.7  3.9  1.2
79   5.7  2.6  3.5  1.0
115  6.4  3.2  5.3  2.3
145  6.7  3.0  5.2  2.3
72   6.3  2.5  4.9  1.5
77   6.7  3.0  5.0  1.7
25   5.0  3.0  1.6  0.2
81   5.5  2.4  3.7  1.0
140  6.7  3.1  5.6  2.4
142  5.8  2.7  5.1  1.9
39   5.1  3.4  1.5  0.2
58   6.6  2.9  4.6  1.3
88   5.6  3.0  4.1  1.3
70   5.9  3.2  4.8  1.8
87   6.3  2.3  4.4  1.3
36   5.5  3.5  1.3  0.2
21   5.1  3.7  1.5  0.4
9    4.9  3.1  1.5  0.1
103  6.3  2.9  5.6  1.8
67   5.8  2.7  4.1  1.0
117  7.7  3.8  6.7  2.2
47   4.6  3.2  1.4  0.2

[112 rows x 4 columns]