In [1]:
# 零起点python机器学习快速入门

In [23]:
import pip
from sklearn.cross_validation import train_test_split
from sklearn.datasets import load_iris
import numpy as np
import pandas as pd
from sklearn.metrics import accuracy_score  
from sklearn.linear_model import LinearRegression

In [9]:
pip_list = pip.get_installed_distributions()

AttributeError: module 'pip' has no attribute 'get_installed_distributions'

In [3]:
iris = load_iris()

In [ ]:
iris

In [10]:
iris.data[0]

array([5.1, 3.5, 1.4, 0.2])

In [4]:
data_df =pd.DataFrame(iris.data,columns=['x1','x2','x3','x4'])

In [25]:
data_df.tail()

x1   x2   x3   x4
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

In [5]:
target_df = pd.DataFrame(iris.target,columns=['xid'])

In [28]:
target_df.tail()

xid
145    2
146    2
147    2
148    2
149    2

In [6]:
df=data_df.copy()

In [30]:
df.tail()

x1   x2   x3   x4
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

In [7]:
df['xid']=iris.target

In [8]:
df.tail()

x1   x2   x3   x4  xid
145  6.7  3.0  5.2  2.3    2
146  6.3  2.5  5.0  1.9    2
147  6.5  3.0  5.2  2.0    2
148  6.2  3.4  5.4  2.3    2
149  5.9  3.0  5.1  1.8    2

In [9]:
df['xid'].value_counts()

2    50
1    50
0    50
Name: xid, dtype: int64

In [10]:
df.loc[df['xid']==0,'name']='virginica'

In [11]:
df.loc[df['xid']==1,'name']='visetosa'

In [12]:
df.loc[df['xid']==2,'name']='versicolor'

In [13]:
df.describe()

x1          x2          x3          x4         xid
count  150.000000  150.000000  150.000000  150.000000  150.000000
mean     5.843333    3.054000    3.758667    1.198667    1.000000
std      0.828066    0.433594    1.764420    0.763161    0.819232
min      4.300000    2.000000    1.000000    0.100000    0.000000
25%      5.100000    2.800000    1.600000    0.300000    0.000000
50%      5.800000    3.000000    4.350000    1.300000    1.000000
75%      6.400000    3.300000    5.100000    1.800000    2.000000
max      7.900000    4.400000    6.900000    2.500000    2.000000

In [24]:
df['name'].value_counts()

virginica     50
versicolor    50
visetosa      50
Name: name, dtype: int64

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
x1      150 non-null float64
x2      150 non-null float64
x3      150 non-null float64
x4      150 non-null float64
xid     150 non-null int32
name    150 non-null object
dtypes: float64(4), int32(1), object(1)
memory usage: 6.5+ KB


In [ ]:
df.head(100)

In [14]:
x=np.arange(16).reshape((4,4))

In [15]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [45]:
d1=pd.DataFrame(x,columns=['a','b','c','d'])

In [46]:
d1

a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [47]:
d1.values

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [50]:
d1[['a']]

a
0   0
1   4
2   8
3  12

In [15]:
x=df[['x1','x2','x3','x4']]
y=df[['xid']]

In [16]:
len(x)

150

In [17]:
len(y)

150

In [18]:
X_train,X_test,y_train,y_test = train_test_split(x,y,random_state=0,test_size=0.3)

In [27]:
X_train.tail()

x1   x2   x3   x4
9    4.9  3.1  1.5  0.1
103  6.3  2.9  5.6  1.8
67   5.8  2.7  4.1  1.0
117  7.7  3.8  6.7  2.2
47   4.6  3.2  1.4  0.2

In [19]:
len(X_train)

105

In [28]:
y_train.tail()

xid
9      0
103    2
67     1
117    2
47     0

In [20]:
linear_mode = LinearRegression()
linear_mode.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [21]:
y_predict = linear_mode.predict(X_test)

In [22]:
y_predict

array([[ 2.07863376],
       [ 0.96669898],
       [-0.15934059],
       [ 1.82209546],
       [-0.03128655],
       [ 2.29167009],
       [-0.03326614],
       [ 1.30556458],
       [ 1.26630691],
       [ 1.10590682],
       [ 1.61291114],
       [ 1.29882172],
       [ 1.24583575],
       [ 1.31726102],
       [ 1.35560867],
       [-0.06446882],
       [ 1.37252277],
       [ 1.26780932],
       [ 0.03810685],
       [-0.05301757],
       [ 1.83345137],
       [ 1.43872911],
       [ 0.11461187],
       [ 0.05223725],
       [ 1.59172014],
       [-0.1067769 ],
       [ 0.16770375],
       [ 1.17090695],
       [ 0.93927314],
       [ 0.10832465],
       [ 1.74781133],
       [ 1.47276913],
       [-0.06720024],
       [ 1.6329574 ],
       [ 2.00469015],
       [ 1.28881924],
       [-0.04616879],
       [ 1.59988104],
       [ 1.30377528],
       [ 1.10489089],
       [ 1.84907488],
       [-0.03240839],
       [ 1.82996938],
       [ 0.21809757],
       [-0.1049876 ]])

In [24]:
accuracy_score(y_test,y_predict)

ValueError: Classification metrics can't handle a mix of multiclass and continuous targets

In [25]:
len(y_predict)

45

In [27]:
len(y_test)

45

In [31]:
for i in y_predict:
    print(i)

[2.07863376]
[0.96669898]
[-0.15934059]
[1.82209546]
[-0.03128655]
[2.29167009]
[-0.03326614]
[1.30556458]
[1.26630691]
[1.10590682]
[1.61291114]
[1.29882172]
[1.24583575]
[1.31726102]
[1.35560867]
[-0.06446882]
[1.37252277]
[1.26780932]
[0.03810685]
[-0.05301757]
[1.83345137]
[1.43872911]
[0.11461187]
[0.05223725]
[1.59172014]
[-0.1067769]
[0.16770375]
[1.17090695]
[0.93927314]
[0.10832465]
[1.74781133]
[1.47276913]
[-0.06720024]
[1.6329574]
[2.00469015]
[1.28881924]
[-0.04616879]
[1.59988104]
[1.30377528]
[1.10489089]
[1.84907488]
[-0.03240839]
[1.82996938]
[0.21809757]
[-0.1049876]


In [32]:
for j in y_test:
    print(j)

xid


In [34]:
y_test.values

array([[2],
       [1],
       [0],
       [2],
       [0],
       [2],
       [0],
       [1],
       [1],
       [1],
       [2],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [2],
       [1],
       [0],
       [0],
       [2],
       [0],
       [0],
       [1],
       [1],
       [0],
       [2],
       [1],
       [0],
       [2],
       [2],
       [1],
       [0],
       [1],
       [1],
       [1],
       [2],
       [0],
       [2],
       [0],
       [0]])